### ISSUE TITLE
Mirrors.json needs resigning

### ISSUE THREAD

**Issue by jmct** [haskell-infra/hackage-root-keys#17]
Hello everyone,

`mirrors.json` needs to be resigned in the next ~36 hours. Apologies for not catching this earlier (at least we caught it before the actual expiration).

I do not have a key to sign, and David C. is current unable to sign.

**Comment by adamgundry** [comment]
@dcoutts ^^

**Comment by jmct** [comment]
I'll also ping @gbaz and @hvr 

It's also worth considering if we should do a bit of spring cleaning of who has keys and whether we should add more people with mirror-signing authority.

**Comment by jmct** [comment]
Thanks @gbaz! We'll do some cleanup/adding of trusted folks when we do the root.json signing in the coming weeks.
